### ISSUE TITLE
GPL-761 BUG - location audit history broken

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/labwhere#257]
**Describe the bug**
The audit history icon on the location page doesn't work.

**To Reproduce**
Steps to reproduce the behaviour:
1. Find a Location you know has Audits related to it (e.g. 'lw-uk-biocentre-box-ap-20-14849')
1. Search for the location barcode in the UI
2. Click on the 'audit history' icon (like a clock with an arrow)
3. Notice the audits do not appear

**Expected behaviour**
Audits should appear on the page

**Screenshots**
![Screenshot 2020-12-02 at 10 25 40](https://user-images.githubusercontent.com/10407809/100860696-be6dde00-3488-11eb-8837-79c50c9cde11.png)

**Comment by stevieing** [comment]
There are no audits. Something has happened in that audits are no longer being recorded for Locations in most places. These need to be added back in as it is making it difficult to troubleshoot.

**Comment by Chris-Friend** [comment]
So yes, there may be several issues here:
* It looks like no new %Location **create** or **update** audit actions have been recorded since late 2017 (Deliberately removed?)
* As of 1st October 2020, the `auditable_type` for location audit entries changed from UnorderedLocation/OrderedLocation to just **Location**. And now any audit with `auditable_type` **Location** can be seen in the UI; otherwise not, e.g. anything before 1st October 2020. I'm guessing the DB query looks for `auditable_type` to **Location**

**Comment by Chris-Friend** [comment]
Fixes:
* No audit actions were being added in the `location_form.rb` when creating/updating/destroying locations. This has been added
* Looks like [this commit](https://github.com/sanger/labwhere/commit/23563c059e450b942e7fb1a7c9999a341537db3e) is the cause of Ordered/UnorderedLocation -> Location auditable_type. Specifically app/models/concerns/auditable.rb line 27. Will fix by adding a migration to convert OrderedLocation or UnorderedLocation auditable_types to Location
