### ISSUE TITLE
DPL-1056 Unable to create buildings in LabWhere [Could've]

### ISSUE THREAD

**Issue by neilsycamore** [sanger/labwhere#701]
When creating a building in LabWhere create location tab the page is loading very slow, once it does load it doesn't create the building. It will return to the same page
![lw_building_page_error](https://github.com/sanger/labwhere/assets/299768/a272d85e-0b98-464e-92f1-727d5e082ffc)

Relates to [RT795753](https://rt.sanger.ac.uk/Ticket/Display.html?id=795753)

Also relates to story DPL-758 https://github.com/sanger/labwhere/issues/649
where the same issue was found when creating rooms

Note: The building require in the RT (RSF) has been created via the console.

**Comment by SHIV5T3R** [comment]
The change in #744 removes the restriction from the task but will still be active because of how the task for generating the restrictions is designed. It will need to be removed manually in the rails console:

Find the restriction and check it's the correct one:

```rb
>>> restriction = Restriction.find_by(validator: "ActiveRecord::Validations::UniquenessValidator")

>>> restriction   # ensure the correct restriction has been selected
```
![image](https://github.com/sanger/labwhere/assets/44001656/28472655-3cfa-4b98-9e57-34a746b74f58)

Then delete the restriction:

```rb
>>> restriction.destroy!
```
