### ISSUE TITLE
Y24-225 - [BUG] LabWhere location child count not updating correctly

### ISSUE THREAD

**Issue by neilsycamore** [sanger/labwhere#813]
There are 129 location instances where the child count is incorrect
`Location.all.filter { |l| l.children_count != l.children.count }.count`
LabWhere is displaying the location's child_count attribute but this is not being updated from location.child.count
![Screenshot 2024-07-29 at 14 47 01](https://github.com/user-attachments/assets/075eeb7f-3fe2-4b75-bee4-addf97ea339a)
Above shows that location Sanger / Sulston / B105 has 9 children where it actually has 8

Acceptance criteria:
- [ ] fix bug (@BenTopping not sure what the bug is??)
- [ ] The incorrect instances are updated
- [ ] Location.all.filter { |l| l.children_count != l.children.count }.count == 0
Contacts
nts, bt8

**Comment by BenTopping** [comment]
Initial research suggests thats Location child_children count is not always in sync with the actual children count. This children_count column is controlled by a gem https://github.com/stefankroes/ancestry so its behaviour is hidden but its reference can be seen in the Location model.

It could be as simple as writing a script to sync up the count but there is a concern as to why it is out of sync. Im not really sure this gem is needed as it doesn't really make sense to store children_count in the db when we can work it out dynamically with higher accuracy. My only thought would be its stored for performance reasons but I don't know if thats the only trade off with removing it?

**Comment by seenanair** [comment]
Findings:

The children_count column is stored in the database for performance reasons, rather than being calculated dynamically. Initially, we managed the hierarchy manually, but this was later replaced by the Ancestry gem (possibly for performance reasons). The issue seems to be that the children_count column is managed by the Ancestry gem, but the gem is not updating it correctly in certain actions. Despite testing various actions like removing, adding, and moving labware/locations between parents, we have been unable to consistently reproduce the specific scenario where this issue occurs.

The assumption is that something might be interfering with the Ancestry gem’s callbacks, potentially custom callbacks (e.g., before_save, after_create, etc.) in the Location model. Since a specific action causing this bug cannot be identified, understanding the root cause has been difficult.

As a generic solution, if the issue arises again, we could try:

- Using prepend in the custom model callbacks. This might ensure that custom model callbacks are executed before the Ancestry gem’s callbacks, allowing the data to remain up-to-date when the Ancestry gem executes its callbacks.
- Investigating if there is a way to force the Ancestry gem to update after all model updates. (This hasn't been found in current research, but a question has been raised in the Ancestry repo as part of this story: https://github.com/stefankroes/ancestry/issues/684)

Currently a rake task is created to fix all out of sync children_count to correct values.

P.S.: Labwhere logs have been checked for errors related to the Ancestry gem, but none were found.
