### ISSUE TITLE
Y24-288 - [BUG] Exception 28/08/2024 at 16:31

### ISSUE THREAD

**Issue by yoldas** [sanger/labwhere#827]
#### Email subject line

[Psd-exceptions] [LabWhere PRODUCTION] location_finder#create (NoMethodError) “undefined method `[]' for nil:NilClass”

#### Error body

```
A No occurred in location_finder#create:

  undefined method `[]' for nil:NilClass
  app/forms/location_finder_form.rb:33:in `assign_params'
```

#### Acceptance Criteria

- [ ] Look into this exception and fix the code to handle the exception sensibly.
- [ ] Document the root cause and solution in a comment on this issue.

#### Additional information
The id of the user who triggered this error is often shown in the exception email, in case you need to communicate with them.

**Comment by BenTopping** [comment]
Fix linked in PR above.

### Cause
When no file was provided on the `find locations` page, and the form was submitted, this error occured.
This is because the logic in the location finder form was not handling missing file cases gracefully.

### Fix
Made the file upload a required field in order to submit the form.
Added error handling in location finder form for dealing with a missing file.
